version: '3.5'

volumes:
  nginx-shared:

services:
  redis:
    image: redis:alpine
    ports:
      - "6389:6379"

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - REDIS_URL="redis://redis:6389"
    depends_on:
      - redis
    ports:
      - "3253:3666"